apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab-cluster-config
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  source:
    path: cluster-config/overlays/lab
    repoURL: https://github.com/phuonghnguyenau/gitops-demo.git
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    automated: null
